/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.arul.belajarjava;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author arulkharisma
 */
public class DiagnosaPenyakitMata extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement ps;
    ResultSet rs;
    
public void kosong(){
    G1.setSelected(false);
    G2.setSelected(false);
    G3.setSelected(false);
    G4.setSelected(false);
    G5.setSelected(false);
    G6.setSelected(false);
    G7.setSelected(false);
    G8.setSelected(false);
    G9.setSelected(false);
    G10.setSelected(false);
    G11.setSelected(false);
    G12.setSelected(false);
    G13.setSelected(false);
    G14.setSelected(false);
    G15.setSelected(false);
    G16.setSelected(false);
    G17.setSelected(false);
    G18.setSelected(false);
    G19.setSelected(false);
    G20.setSelected(false);
    G21.setSelected(false);
    G22.setSelected(false);
    G23.setSelected(false);
    G24.setSelected(false);
    G25.setSelected(false);
    G26.setSelected(false);
    G27.setSelected(false);
    G28.setSelected(false);
    }

    /**
     * Creates new form DiagnosaPenyakitMata
     */
    public DiagnosaPenyakitMata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        dataUser = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        G1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        G2 = new javax.swing.JCheckBox();
        G3 = new javax.swing.JCheckBox();
        G4 = new javax.swing.JCheckBox();
        G5 = new javax.swing.JCheckBox();
        G6 = new javax.swing.JCheckBox();
        G7 = new javax.swing.JCheckBox();
        G8 = new javax.swing.JCheckBox();
        G9 = new javax.swing.JCheckBox();
        G10 = new javax.swing.JCheckBox();
        G12 = new javax.swing.JCheckBox();
        G13 = new javax.swing.JCheckBox();
        G14 = new javax.swing.JCheckBox();
        G15 = new javax.swing.JCheckBox();
        G16 = new javax.swing.JCheckBox();
        G17 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        G18 = new javax.swing.JCheckBox();
        G19 = new javax.swing.JCheckBox();
        G20 = new javax.swing.JCheckBox();
        G21 = new javax.swing.JCheckBox();
        G22 = new javax.swing.JCheckBox();
        G23 = new javax.swing.JCheckBox();
        G24 = new javax.swing.JCheckBox();
        G25 = new javax.swing.JCheckBox();
        G26 = new javax.swing.JCheckBox();
        G27 = new javax.swing.JCheckBox();
        G28 = new javax.swing.JCheckBox();
        G11 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SPK Diagnosa Penyakit");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        dataUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dataUser.setForeground(new java.awt.Color(255, 255, 255));
        dataUser.setIcon(new javax.swing.ImageIcon("C:\\Users\\arulkharisma\\OneDrive\\Documents\\NetBeansProjects\\SPK-DiagnosaPenyakit\\src\\main\\java\\com\\arul\\belajarjava\\account (1).png")); // NOI18N
        dataUser.setText("Arul Kharisma");
        dataUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataUserMouseClicked(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Menu");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Diagnosa Penyakit Jantung");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Diagnosa Penyakit Mata");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\arulkharisma\\OneDrive\\Documents\\NetBeansProjects\\SPK-DiagnosaPenyakit\\src\\main\\java\\com\\arul\\belajarjava\\logout (1).png")); // NOI18N
        jLabel2.setText("Logout");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\arulkharisma\\OneDrive\\Documents\\NetBeansProjects\\SPK-DiagnosaPenyakit\\src\\main\\java\\com\\arul\\belajarjava\\puzzle.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(2, 28, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataUser)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(116, 116, 116)))
                .addGap(25, 25, 25))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataUser, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(14, 14, 14))
        );

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        G1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G1.setText("Mata Merah");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Isi gejala sedetail mungkin, untuk hasil yang lebih akurat !! ");

        G2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G2.setText("Mata Berair");

        G3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G3.setText("Nyeri Mata");

        G4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G4.setText("Sensitive Terhadap Cahaya");

        G5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G5.setText("Pandangan Kabur");

        G6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G6.setText("Terasa benda asing didalam mata /mengganjal");
        G6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G6ActionPerformed(evt);
            }
        });

        G7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G7.setText("Riwayat mata terkena lumpur");

        G8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G8.setText("pernah/masih memakai lensa kontak");

        G9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G9.setText("Terdapat bintik putih pada kornea");

        G10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G10.setText("pembengkakan kelopak mata");

        G12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G12.setText("tampak nanah didalam bola mata");
        G12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G12ActionPerformed(evt);
            }
        });

        G13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G13.setText("riwayat mata pernah terkena tanaman(daun/serbuk kayu)");

        G14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G14.setText("Sakit mata tampak setelah 2 minggu lebih");

        G15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G15.setText("Kehilangan penglihatan/buta");

        G16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G16.setText("iritasi mata");

        G17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G17.setText("Mata gatal");

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Hasil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        G18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G18.setText("Terdapat jaringan putih pada sudut dalam mata");

        G19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G19.setText("Pembengkakan pada kornea");

        G20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G20.setText("Mata terasa sangat nyeri sekali");

        G21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G21.setText("Terdapat putih putih seperti cincin dimata");

        G22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G22.setText("sedang atau mengalami batuk/pilek");

        G23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G23.setText("Mata lengket dipagi hari");

        G24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G24.setText("pernah melihat sinar las/terkena benda kimia");

        G25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G25.setText("Keluhan saat itu juga setelah terkena bahan kimia");

        G26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G26.setText("Tampak putih di tengah dan pinggir mata");

        G27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G27.setText("Mata kering");

        G28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G28.setText("Tampak seperti daging yang menutupi mata");

        G11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G11.setText("Salah satu mata yang terkena");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(G1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(G18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(G28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(G17, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addContainerGap())))
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel6)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(G1)
                            .addComponent(G17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(G18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(G2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G11)
                                .addGap(6, 6, 6)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(G12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G16)
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2)
                                    .addComponent(jButton3)))
                            .addComponent(G28)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    conn = Koneksi.sambung();
    dataUser.setText(UserSession.getNama());
    }//GEN-LAST:event_formWindowOpened

    private void G6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G6ActionPerformed

    private void G12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G12ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    UserHome kembali = new UserHome();
    kembali.setVisible(true);
    dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String mysql = "insert into gejala values(null,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
    
    
    if(G1.isSelected()){
    G1.setText("✓");
    }else{
    G1.setText("x");
    }
    
    if(G2.isSelected()){
    G2.setText("✓");
    }else{
    G2.setText("x");
    }
    
    if(G3.isSelected()){
    G3.setText("✓");
    }else{
    G3.setText("x");
    }
    
    if(G4.isSelected()){
    G4.setText("✓");
    }else{
    G4.setText("x");
    }
       
    if(G5.isSelected()){
    G5.setText("✓");
    }else{
    G5.setText("x");
    }
    
    if(G6.isSelected()){
    G6.setText("✓");
    }else{
    G6.setText("x");
    }
    
    if(G7.isSelected()){
    G7.setText("✓");
    }else{
    G7.setText("x");
    }
    
    if(G8.isSelected()){
    G8.setText("✓");
    }else{
    G8.setText("x");
    }
    
    if(G9.isSelected()){
    G9.setText("✓");
    }else{
    G9.setText("x");
    }
    
    if(G10.isSelected()){
    G10.setText("✓");
    }else{
    G10.setText("x");
    }
    
    if(G11.isSelected()){
    G11.setText("✓");
    }else{
    G11.setText("x");
    }
    
    if(G12.isSelected()){
    G12.setText("✓");
    }else{
    G12.setText("x");
    }
    
    if(G13.isSelected()){
    G13.setText("✓");
    }else{
    G13.setText("x");
    }
    
    if(G14.isSelected()){
    G14.setText("✓");
    }else{
    G14.setText("x");
    }
    
    if(G15.isSelected()){
    G15.setText("✓");
    }else{
    G15.setText("x");
    }
    
    if(G16.isSelected()){
    G16.setText("✓");
    }else{
    G16.setText("x");
    }
    
    if(G17.isSelected()){
    G17.setText("✓");
    }else{
    G17.setText("x");
    }
    
    if(G18.isSelected()){
    G18.setText("✓");
    }else{
    G18.setText("x");
    }
    
    if(G19.isSelected()){
    G19.setText("✓");
    }else{
    G19.setText("x");
    }
    
    if(G20.isSelected()){
    G20.setText("✓");
    }else{
    G20.setText("x");
    }
    
    if(G21.isSelected()){
    G22.setText("✓");
    }else{
    G21.setText("x");
    }
    
    if(G22.isSelected()){
    G22.setText("✓");
    }else{
    G22.setText("x");
    }
    
    if(G23.isSelected()){
    G23.setText("✓");
    }else{
    G23.setText("x");
    }
    
    if(G24.isSelected()){
    G24.setText("✓");
    }else{
    G24.setText("x");
    }
    
    if(G25.isSelected()){
    G25.setText("✓");
    }else{
    G25.setText("x");
    }
    
    if(G26.isSelected()){
    G26.setText("✓");
    }else{
    G26.setText("x");
    }
    
    if(G27.isSelected()){
    G27.setText("✓");
    }else{
    G27.setText("x");
    }
    
    if(G28.isSelected()){
    G28.setText("✓");
    }else{
    G28.setText("x");
    }
    
   try {
    String hasil;
    String nama = UserSession.getNama();
    
    if((G1.isSelected() && G3.isSelected() && G8.isSelected()) || (G1.isSelected() && G8.isSelected()) 
        || (G1.isSelected() && G9.isSelected()) || (G1.isSelected() && G10.isSelected()) || (G1.isSelected() && G11.isSelected()) || (G1.isSelected() && G12.isSelected())
        || (G1.isSelected() && G2.isSelected() && G3.isSelected()) || (G1.isSelected() && G8.isSelected() && G9.isSelected() && G10.isSelected() && G11.isSelected() && G12.isSelected())){
        hasil ="Kemungkinan terbesar hasil diagnosa atas nama pasien " + nama +" adalah penyakit KRETITIS BAKTERIALIS dengan presentase kecocokan terhadap gejala lebih besar";
    }else if((G3.isSelected() && G5.isSelected()) || (G1.isSelected() && G3.isSelected()) || (G1.isSelected() && G3.isSelected() &&G5.isSelected())){
        hasil="Kemungkinan terbesar hasil diagnosa atas nama pasien " + nama + " adalah penyakit KERATITIS JAMUR (KERATOMIKOS) dengan presentase\n kecocokan terhadap gejala lebih besar";
    }else if((G2.isSelected() && G4.isSelected()) || (G2.isSelected() && G6.isSelected()) || (G4.isSelected() && G6.isSelected()) || (G2.isSelected() && G4.isSelected() && G6.isSelected())){
        hasil ="Kemungkinan terbesar hasil diagnosa atas nama pasien " + nama +"  adalah penyakit PTERIGIUM dengan presentase kecocokan terhadap gejala lebih besar";
    }else if((G2.isSelected() && G5.isSelected()) || (G2.isSelected() && G7.isSelected()) || (G5.isSelected() && G7.isSelected()) || (G2.isSelected() && G5.isSelected() && G7.isSelected())){
        hasil ="Kemungkinan terbesar hasil diagnosa atas nama pasien " + nama +"  adalah penyakit KERATITIS HERPES dengan presentase kecocokan terhadap gejala lebih besar";
    }else if((G1.isSelected() && G3.isSelected()) || (G1.isSelected() && G4.isSelected()) || (G1.isSelected() && G5.isSelected()) || (G3.isSelected() && G4.isSelected()) || (G3.isSelected() && G5.isSelected()) || (G4.isSelected() && G5.isSelected()) 
            || (G1.isSelected() && G3.isSelected() && G4.isSelected()) || (G1.isSelected() && G3.isSelected() && G5.isSelected()) || (G3.isSelected() && G4.isSelected() && G5.isSelected()) 
            || (G1.isSelected() && G3.isSelected() && G4.isSelected() && G5.isSelected())){
        hasil ="Kemungkinan terbesar hasil diagnosa atas nama pasien " + nama +"  adalah penyakit KERATITIS ACANTHAMOEBA dengan presentase kecocokan terhadap gejala lebih besar";
    }else if((G1.isSelected() && G2.isSelected()) || (G1.isSelected() && G5.isSelected()) || (G1.isSelected() && G22.isSelected()) || (G1.isSelected() && G23.isSelected()) || (G1.isSelected() && G24.isSelected()) 
            || (G1.isSelected() && G25.isSelected()) || (G1.isSelected() && G2.isSelected() && G5.isSelected() && G22.isSelected() && G23.isSelected()) && G24.isSelected() && G25.isSelected()){
    hasil ="Kemungkinan terbesar hasil diagnosa atas nama pasien " + nama +"  adalah penyakit KERATOKONJUNGSITIVITIS (EPEDEMIKA) dengan presentase kecocokan terhadap gejala lebih besar";
    }else if((G1.isSelected() && G2.isSelected() && G26.isSelected()) || (G1.isSelected() && G26.isSelected()) || (G1.isSelected() && G27.isSelected()) || (G2.isSelected() && G26.isSelected()) || (G2.isSelected() && G27.isSelected())
            || (G1.isSelected() && G2.isSelected() && G26.isSelected() && G27.isSelected())){
    hasil ="Kemungkinan terbesar hasil diagnosa atas nama pasien " + nama +" adalah penyakit EROSI KORNEA dengan presentase kecocokan terhadap gejala lebih besar";
    }else{
    hasil ="atas nama pasien " + nama +", kami tidak dapat menentukan diagnosa penyakit karena data yang dimasukkan tidak sinkron";
    }
    
        
            ps = conn.prepareStatement(mysql);
            ps.setInt(1, UserSession.getid());
//          ps.setString(2, G1.getText()+G2.getText());
            ps.setString(2, G1.getText());
            ps.setString(3, G2.getText());
            ps.setString(4, G3.getText());
            ps.setString(5, G4.getText());
            ps.setString(6, G5.getText());  
            ps.setString(7, G6.getText());
            ps.setString(8, G7.getText());
            ps.setString(9, G8.getText());
            ps.setString(10, G9.getText());
            ps.setString(11, G10.getText());
            ps.setString(12, G11.getText());
            ps.setString(13, G12.getText());
            ps.setString(14, G13.getText());
            ps.setString(15, G14.getText());
            ps.setString(16, G15.getText());  
            ps.setString(17, G16.getText());
            ps.setString(18, G17.getText());
            ps.setString(19, G18.getText());
            ps.setString(20, G19.getText());
            ps.setString(21, G20.getText());
            ps.setString(22, G21.getText());
            ps.setString(23, G22.getText());
            ps.setString(24, G23.getText());
            ps.setString(25, G24.getText());
            ps.setString(26, G25.getText());  
            ps.setString(27, G26.getText());
            ps.setString(28, G27.getText());
            ps.setString(29, G28.getText());
            ps.setString(30, hasil);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "klik OK untuk melanjutkan ");
            HasilLaporan to = new HasilLaporan();
            to.setVisible(true);
            dispose();
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    kosong();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        UserLogin kembali = new UserLogin();
        kembali.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        DiagnosaPenyakitMata kembali = new DiagnosaPenyakitMata();
        kembali.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        DiagnosaPenyakitJantung kembali = new DiagnosaPenyakitJantung();
        kembali.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void dataUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataUserMouseClicked
        UserHome kembali = new UserHome();
        kembali.setVisible(true);
        dispose();
    }//GEN-LAST:event_dataUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagnosaPenyakitMata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagnosaPenyakitMata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagnosaPenyakitMata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagnosaPenyakitMata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiagnosaPenyakitMata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox G1;
    private javax.swing.JCheckBox G10;
    private javax.swing.JCheckBox G11;
    private javax.swing.JCheckBox G12;
    private javax.swing.JCheckBox G13;
    private javax.swing.JCheckBox G14;
    private javax.swing.JCheckBox G15;
    private javax.swing.JCheckBox G16;
    private javax.swing.JCheckBox G17;
    private javax.swing.JCheckBox G18;
    private javax.swing.JCheckBox G19;
    private javax.swing.JCheckBox G2;
    private javax.swing.JCheckBox G20;
    private javax.swing.JCheckBox G21;
    private javax.swing.JCheckBox G22;
    private javax.swing.JCheckBox G23;
    private javax.swing.JCheckBox G24;
    private javax.swing.JCheckBox G25;
    private javax.swing.JCheckBox G26;
    private javax.swing.JCheckBox G27;
    private javax.swing.JCheckBox G28;
    private javax.swing.JCheckBox G3;
    private javax.swing.JCheckBox G4;
    private javax.swing.JCheckBox G5;
    private javax.swing.JCheckBox G6;
    private javax.swing.JCheckBox G7;
    private javax.swing.JCheckBox G8;
    private javax.swing.JCheckBox G9;
    private javax.swing.JLabel dataUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
